### ISSUE TITLE
When the dataset is to big it eats a lot of memory and crashes

### ISSUE THREAD

**Issue by giventofly** [PHPJuice/slopeone#7]
I imagine there is no simple workaround for this issue, since the calculation matrix gets huge, but can some some sort of calculation steps be made?

Like, take the first 10 calculate for them, loop for the rest and then, do the final calculation with the resulting dataset?

**Comment by mhdcodes** [comment]
This algorithm is not meant for large datasets, since small to medium datasets can provide you with good enough predictions, I would say to solve you issue you need to segment your users into groups and perform predictions with only a subset of users ratings or calculate the model and save it somewhere.

**Comment by giventofly** [comment]
I did a partial solution partitioning the dataset and making smaller datasets, and get all the predictions (using an empty item to check), but over time it gets eventually way big too.

Thank you for your time and contribution, very useful.
